### ISSUE TITLE
have symbol equal in the value property

### ISSUE THREAD

**Issue by wsf1991** [magiconair/properties#13] opened 2016-07-12 19:11 UTC
Hi I ran into this issue from eBay fabio, i want to set property 'registry.consul.register.tags'. i.e. "key1=val1" as one of the tag, but it has this kind of error:
[FATAL] 1.1.5. circular reference

is that a way to escape equal symbol. thanks

**Comment by magiconair** [comment] 2016-07-12 20:41
The backslash should do the trick. Let me know if it doesn't then I'll have a look in one of the next days.

**Comment by magiconair** [comment] 2016-07-13 12:43
Hmm, tested this with both fabio 1.1.5 and 1.1.6 and cannot reproduce this. However, I do noticed that the current 1.2 branch has a bug in that it does not register the tags at all.

```
# cat fabio.properties
...
registry.consul.register.tags = key1=val1
```

```
# ./fabio -cfg fabio.properties
...
2016/07/13 13:37:28 [INFO] consul: Registered fabio with tags "key1=val1"
...
```

**Comment by magiconair** [comment] 2016-07-13 15:14
@wsf1991 : 1.2 does not have a bug. I just started it wrong. Can you provide a more detailed example, please? Otherwise, I'm going to close this.

**Comment by wsf1991** [comment] 2016-07-13 20:36
Hi Frank,

I pull Fabio master branch and set tags of Fabio registered in consul as key1=${env_var}, ...

Let me attach the error info later today. Thanks.

Regards,
Shifei Wu

**Comment by magiconair** [comment] 2016-07-14 08:10
ok, good since I can't reproduce that behavior either.

**Comment by magiconair** [comment] 2016-07-25 12:02
I'll close this one for now. Please re-open if you have more information.

**Closed by magiconair** 2016-07-25 12:02 UTC
Labels: need response
